name: Compile LaTeX to PDF

on:
    push:
        paths:
            - "docs/**"
        branches:
            - main

    workflow_dispatch:

permissions:
    contents: write

jobs:
    build_latex:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install LaTeX dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-bibtex-extra

            - name: Compile LaTeX document
              uses: xu-cheng/latex-action@v3
              with:
                  root_file: main.tex
                  working_directory: docs
                  latexmk_args: -pdf -bibtex -f

            - name: Set up Git
              run: |
                  git config --global user.name "GitHub Actions [bot]"
                  git config --global user.email "noreply@github.com"

            - name: Commit and push changes
              run: |
                  git add docs/pdf/main.pdf
                  COMMIT_MSG="Auto-update PDF documentation from commit ${GITHUB_SHA::8}"
                  git commit -m "$COMMIT_MSG" || echo "No changes to commit"
                  git push
