name: Update Submodules

on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:

jobs:
    update-submodule:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive

            - name: Git Submodule Update
              run: |
                  git pull --recurse-submodules
                  git submodule update --remote --recursive

            - uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: "update submodules"
                  commit_user_name: "Submodule updater"
                  commit_author: "Submodule updater"
